build() {
add_module cdrom
add_module loop
add_module squashfs
add_module dm-snapshot
add_module overlay

add_runscript

add_binary blkid
add_binary losetup 
add_binary /usr/lib/udev/cdrom_id
add_binary blockdev
add_binary dmsetup 
add_binary truncate
add_binary grep

add_file /usr/lib/udev/rules.d/60-cdrom_id.rules
add_file /usr/lib/udev/rules.d/10-dm.rules
add_file /usr/lib/udev/rules.d/95-dm-notify.rules
add_file /usr/lib/initcpio/udev/11-dm-initramfs.rules 

}
